name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20.x'
      - run: go mod download
      - run: go install github.com/securego/gosec/v2/cmd/gosec@latest
      - run: gosec ./...
      - run: go test ./...
